### ISSUE TITLE
Generating provenance file,  path not found error

### ISSUE THREAD

**Issue by iolivergithub** [slsa-framework/github-actions-demo#30]
More guidance on how to integrate the action is required. We have an action to build a docker container:

```
name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file a10rest/Dockerfile.local --tag a10rest:$(date +%s)
    - uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: /a10rest
        output_path: a10rest.provenance
      continue-on-error: true
```

The integration of the sla-framework action above is an educated guess from the instructions, but it runs. The artifact path however is a mystery: we've tried paths, relative paths and the name of the generated container (tag), but are unsure exactly how to refer to the artifact.

The above action run with the slsa action producing the error  in this case `Resource path not found: [provided=/a10rest]``
